@ECHO OFF
SETLOCAL
  CALL :NORMALIZEPATH "C:\dev-tools\bin\msvc-no-vcvars"
  PUSHD %RETVAL%
    CALL "setup_cl_generic.bat" x64
  POPD

  SET NO_OUTPUT=^>nul 2^>nul
  SET PROJECT_ALIAS=test

  SET PREPROCESSOR=/D_CRT_SECURE_NO_WARNINGS
  SET EXCEPTIONS=/GR- /EHa-
  SET WARNINGS=/WX /Wall /wd4710 /wd4189 /wd4101 /wd4244 /wd4711 /wd5045

  SET SUBSYSTEM=/SUBSYSTEM:CONSOLE

  SET COMMON_COMPILER_FLAGS=%PREPROCESSOR% /nologo %EXCEPTIONS% ^
                            %SECURITY% %WARNINGS% /FC
  SET COMMON_LINKER_FLAGS=/INCREMENTAL:NO /OPT:REF %SUBSYSTEM%
  SET OPTIMIZATION_MODE=/O2


  CL ^
    %COMMON_COMPILER_FLAGS% %OPTIMIZATION_MODE% ^
    /Z7 "%PROJECT_ALIAS%.c" ^
    %INTERNAL_LIBS% /link %COMMON_LINKER_FLAGS%

ENDLOCAL

:: ========== FUNCTIONS ==========
EXIT /B

:NORMALIZEPATH
  SET RETVAL=%~f1
  GOTO :EOF
